/**
 * films-data.js — Data film bersama untuk CineGo
 * Dimuat sebelum home.js dan trending.js di semua halaman.
 */

const FILMS_TR = [
  {
    id: 1,
    film: "Siksa Kubur",
    genre: "Horror / Drama",
    tags: ["Horror", "Drama"],
    durasi: 117,
    rating: 8.2,
    tahun: 2024,
    sutradara: "Joko Anwar",
    pemain: "Faradina Mufti, Reza Rahadian, Slamet Rahardjo",
    sinopsis:
      "Sita adalah seorang wanita ateis yang keras kepala. Untuk membuktikan bahwa siksa kubur hanyalah isapan jempol belaka, ia memutuskan mengalaminya sendiri — dan apa yang ia temukan di sana mengubah segalanya.",
    poster: "Images/siksa-kubur.jpg",
    bookingKey: "Siksa+Kubur",
    baseVotes: 1240,
  },
  {
    id: 2,
    film: "A Minecraft Movie",
    genre: "Adventure / Fantasy",
    tags: ["Adventure", "Fantasy", "Family"],
    durasi: 101,
    rating: 7.8,
    tahun: 2025,
    sutradara: "Jared Hess",
    pemain: "Jack Black, Jason Momoa, Jennifer Coolidge",
    sinopsis:
      "Empat orang tersedot ke dalam dunia balok bernama Overworld dan harus berjuang untuk bertahan hidup. Satu-satunya harapan mereka adalah seorang pahlawan tak terduga bernama Steve.",
    poster: "Images/a-minecraft-movie-movie-poster.jpg",
    bookingKey: "A+Minecraft+Movie",
    baseVotes: 980,
  },
  {
    id: 3,
    film: "Agak Laen",
    genre: "Horror / Comedy",
    tags: ["Horror", "Comedy"],
    durasi: 119,
    rating: 8.5,
    tahun: 2024,
    sutradara: "Muhadkly Acho",
    pemain: "Bene Dion, Oki Rengga, Dimas Anggara, Indra Jegel",
    sinopsis:
      "Empat sahabat pengelola rumah hantu ketiban sial saat dukun sewaan mereka tewas di dalam wahana. Sosok sang dukun pun mulai gentayangan, membuat terror nyata bagi mereka sendiri.",
    poster: "Images/agak-laen.jpg",
    bookingKey: "Agak+Laen",
    baseVotes: 870,
  },
  {
    id: 4,
    film: "Avengers: Infinity War",
    genre: "Action / Sci-Fi",
    tags: ["Action", "Sci-Fi", "Marvel"],
    durasi: 149,
    rating: 8.4,
    tahun: 2018,
    sutradara: "Anthony & Joe Russo",
    pemain: "Robert Downey Jr., Chris Evans, Chris Hemsworth, Scarlett Johansson",
    sinopsis:
      "Thanos berusaha mengumpulkan enam Infinity Stones untuk memusnahkan setengah populasi alam semesta. Para Avengers bersatu dalam pertempuran paling epik untuk menghentikannya.",
    poster: "Images/infinity.jpg",
    bookingKey: "Avengers%3A+Infinity+War",
    baseVotes: 760,
  },
  {
    id: 5,
    film: "Jumbo",
    genre: "Animation / Adventure",
    tags: ["Animation", "Family", "Adventure"],
    durasi: 102,
    rating: 8.0,
    tahun: 2025,
    sutradara: "Ryan Andriandhy",
    pemain: "Angga Yunanda, Prilly Latuconsina",
    sinopsis:
      "Si kecil Don bersahabat dengan sosok misterius bernama Jumbo. Petualangan ajaib mereka membawa pelajaran berharga tentang persahabatan, keberanian, dan makna keluarga yang sesungguhnya.",
    poster: "Images/jumbo-indonesian-movie-poster.jpg",
    bookingKey: "Jumbo",
    baseVotes: 620,
  },
  {
    id: 6,
    film: "Ancika: 1995",
    genre: "Romance / Drama",
    tags: ["Romance", "Drama"],
    durasi: 100,
    rating: 7.9,
    tahun: 2023,
    sutradara: "Benni Setiawan",
    pemain: "Marthino Lio, Raisa Andriana",
    sinopsis:
      "Kisah cinta Dilan dan Ancika di Bandung tahun 1995. Dilan harus membuktikan dirinya kepada gadis yang memiliki kepribadian kuat, mandiri, dan tidak mudah takluk oleh rayuan.",
    poster: "Images/ancika-1995.jpg",
    bookingKey: "Ancika%3A+1995",
    baseVotes: 510,
  },
  {
    id: 7,
    film: "Mission: Impossible \u2013 The Final Reckoning",
    genre: "Action / Thriller",
    tags: ["Action", "Thriller"],
    durasi: 169,
    rating: 8.3,
    tahun: 2025,
    sutradara: "Christopher McQuarrie",
    pemain: "Tom Cruise, Hayley Atwell, Simon Pegg, Ving Rhames",
    sinopsis:
      "Ethan Hunt menghadapi ancaman terbesar sepanjang kariernya — sebuah AI bernama The Entity yang mampu mengendalikan seluruh persenjataan nuklir global. Ini misi terakhir, dengan taruhan tertinggi.",
    poster: "Images/25MIFR.jpg",
    bookingKey: "Mission%3A+Impossible+%E2%80%93+The+Final+Reckoning",
    baseVotes: 445,
  },
  {
    id: 8,
    film: "Fantastic Four: First Steps",
    genre: "Action / Sci-Fi",
    tags: ["Action", "Sci-Fi", "Marvel"],
    durasi: 130,
    rating: 0,
    tahun: 2026,
    sutradara: "Matt Shakman",
    pemain: "Pedro Pascal, Vanessa Kirby, Joseph Quinn, Ebon Moss-Bachrach",
    sinopsis:
      "Keluarga super pertama Marvel — Reed Richards, Sue Storm, Johnny Storm, dan Ben Grimm — memulai petualangan luar angkasa mereka yang mengubah segalanya. Menghadapi ancaman kosmik yang belum pernah ada sebelumnya, mereka harus belajar bekerja sebagai satu kesatuan.",
    poster: "Images/fantastic 4.jpg",
    bookingKey: "Fantastic+Four%3A+First+Steps",
    baseVotes: 380,
    comingSoon: true,
    rilisLabel: "1 Juli 2026",
  },
  {
    id: 9,
    film: "Jurassic World Rebirth",
    genre: "Action / Adventure",
    tags: ["Action", "Adventure", "Thriller"],
    durasi: 125,
    rating: 0,
    tahun: 2026,
    sutradara: "Gareth Edwards",
    pemain: "Scarlett Johansson, Jonathan Bailey, Mahershala Ali",
    sinopsis:
      "Lima tahun setelah peristiwa Jurassic World Dominion, sebuah misi rahasia dikirim ke pulau terpencil yang masih dihuni dinosaurus. Apa yang mereka temukan di sana jauh lebih berbahaya dari yang dibayangkan.",
    poster: "Images/Jurassic world.jpg",
    bookingKey: "Jurassic+World+Rebirth",
    baseVotes: 320,
    comingSoon: true,
    rilisLabel: "3 Juli 2026",
  },
  {
    id: 10,
    film: "Superman: Legacy",
    genre: "Action / Superhero",
    tags: ["Action", "Sci-Fi", "DC"],
    durasi: 138,
    rating: 0,
    tahun: 2026,
    sutradara: "James Gunn",
    pemain: "David Corenswet, Rachel Brosnahan, Nicholas Hoult",
    sinopsis:
      "Clark Kent memulai perjalanannya sebagai Superman — sang pahlawan yang menyeimbangkan warisan Kryptonian-nya dengan identitasnya sebagai manusia Kansas. Sebuah babak baru semesta DC dimulai.",
    poster: "Images/Superman.jpg",
    bookingKey: "Superman%3A+Legacy",
    baseVotes: 290,
    comingSoon: true,
    rilisLabel: "8 Juli 2026",
  },
  {
    id: 11,
    film: "The Batman Part II",
    genre: "Action / Thriller",
    tags: ["Action", "Thriller", "DC"],
    durasi: 165,
    rating: 0,
    tahun: 2026,
    sutradara: "Matt Reeves",
    pemain: "Robert Pattinson, Zoë Kravitz, Barry Keoghan",
    sinopsis:
      "Bruce Wayne kembali menghadapi Gotham yang lebih gelap. Setelah kejatuhan Riddler, kekuatan baru bangkit dari bayang-bayang kota — dan The Batman harus menghadapi ujian terberat dalam hidupnya.",
    poster: "Images/Batman II.jpg",
    bookingKey: "The+Batman+Part+II",
    baseVotes: 245,
    comingSoon: true,
    rilisLabel: "10 Juli 2026",
  },
];
